apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  POSTGRES_PASSWORD: aGdmaDUzNXQ=
  JWT_SECRET_KEY: a2pyZ2kvODVyZyo=
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpoZ2ZoNTM1dEBkYi1hdXRoOjU0MzIvYXV0aF9zdmM=
  POSTGRES_USER: cG9zdGdyZXM=