apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  labels:
    reloader: enabled
  {{- include "helmcharts.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: aGdmaDUzNXQ=
  JWT_SECRET_KEY: a2pyZ2kvODVyZyo=
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpoZ2ZoNTM1dEBkYi1hdXRoLXBvc3RncmVzcWw6NTQzMi9hdXRoX3N2Yw==
type: Opaque