apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true, Force=true
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: /tmp/hostpath-provisioner/db-persistent-volume-claim-auth
    type: DirectoryOrCreate
  storageClassName:  {{ .Values.pvc.dbPersistentVolumeClaim.storageClass | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dbPersistentVolumeClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.dbPersistentVolumeClaim.storageClass | quote }}