apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-microservice
  labels:
    app: product-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-microservice
  template:
    metadata:
      labels:
        app: product-microservice
    spec:
      containers:
      - name: product-microservice
        image: raniamidaoui/goMart-product-service:latest
        ports:
        - containerPort: 50052
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: product-config
                key: DB_HOST

          - name: PRODUCT_SERVICE_URL
            value: product-microservice

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: product-config
                key: DB_PORT

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: POSTGRES_PASSWORD

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: product-config
                key: POSTGRES_DB

          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: DB_URL