apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  labels:
    reloader: enabled
  {{- include "helmcharts.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: ZmdkZ2Qz
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpmZ2RnZDNAZGItcHJvZHVjdC1wb3N0Z3Jlc3FsOjU0MzIvcHJvZHVjdF9zdmM=
type: Opaque