apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-pv
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: /tmp/hostpath-provisioner/db-product-persistent-volume-claim-product
    type: DirectoryOrCreate
  storageClassName: {{ .Values.pvc.dbPersistentVolumeClaim.storageClass | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-product-persistent-volume-claim
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dbPersistentVolumeClaim.storageRequest | quote
        }}
  storageClassName: {{ .Values.pvc.dbPersistentVolumeClaim.storageClass |
    quote }}