apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  labels:
    reloader: enabled
  {{- include "helmcharts.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.productConfig.dbHost | quote }}
  DB_PORT: {{ .Values.productConfig.dbPort | quote }}
  POSTGRES_DB: {{ .Values.productConfig.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.productConfig.postgresUser | quote }}