apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  POSTGRES_PASSWORD: ZmdkZ2Qz
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpmZ2RnZDNAZGItcHJvZHVjdDo1NDMyL3Byb2R1Y3Rfc3Zj
  POSTGRES_USER: cG9zdGdyZXM=