{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gomart.io
    http:
      paths:
      - backend:
          service:
            name: 'api-gateway'
            port:
              number: 3000
        path: /
        pathType: Prefix
{{- end}}
