apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.type }}
  selector:
    app: api-gateway
  {{- include "helmcharts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.apiGateway.ports | toYaml | nindent 2 -}}