apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  labels:
    app: order-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: raniamidaoui/goMart-order-service:latest
        ports:
        - containerPort: 50053
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: DB_HOST

          - name: PRODUCT_SERVICE_URL
            value: product-microservice:50052

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: DB_PORT

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: POSTGRES_PASSWORD

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: order-config
                key: POSTGRES_DB

          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: DB_URL