apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  labels:
    reloader: enabled
  {{- include "helmcharts.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.orderConfig.dbHost | quote }}
  DB_PORT: {{ .Values.orderConfig.dbPort | quote }}
  POSTGRES_DB: {{ .Values.orderConfig.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.orderConfig.postgresUser | quote }}