apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  labels:
    reloader: enabled
  {{- include "helmcharts.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: ZWFkdWE3cg==
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczplYWR1YTdyQGRiLW9yZGVyLXBvc3RncmVzcWw6NTQzMi9vcmRlcl9zdmM=
type: Opaque