apiVersion: v1
kind: Service
metadata:
  name: order-microservice
  labels:
  {{- include "helmcharts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orderMicroservice.type }}
  selector:
    app: order-microservice
  {{- include "helmcharts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.orderMicroservice.ports | toYaml | nindent 2 -}}