apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  POSTGRES_PASSWORD: ZWFkdWE3cg==
  DB_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczplYWR1YTdyQGRiLW9yZGVyOjU0MzIvb3JkZXJfc3Zj
  POSTGRES_USER: cG9zdGdyZXM=